export default {
	ready() {
		this.bankList = [{
			name: '中国工商银行',
			icon: 'bank_gs.png',
			value: 1002
		}, {
			name: '中国农业银行',
			icon: 'bank_ny.jpg',
			value: 1005
		}, {
			name: '中国银行',
			icon: 'bank_zg.png',
			value: 1052
		}, {
			name: '中国建设银行',
			icon: 'bank_js.png',
			value: 1003
		}, {
			name: '招商银行',
			icon: 'bank_zs.jpg',
			value: 1001
		}, {
			name: '浦发银行',
			icon: 'bank_pf.jpg',
			value: 1004
		}, {
			name: '中国民生银行',
			icon: 'bank_ms.jpg',
			value: 1006
		}, {
			name: '兴业银行',
			icon: 'bank_xy.jpg',
			value: 1009
		}, {
			name: '中国光大银行',
			icon: 'bank_gd.jpg',
			value: 1022
		}, {
			name: '平安银行',
			icon: 'bank_pn.jpg',
			value: 1010
		}, {
			name: '中信银行',
			icon: 'bank_zx.png',
			value: 1021
		}, {
			name: '华夏银行',
			icon: 'bank_hx.jpg',
			value: 1025
		}, {
			name: '中国邮政蓄储银行',
			icon: 'bank_yz.jpg',
			value: 1028
		}, {
			name: '广发银行',
			icon: 'bank_gf.jpg',
			value: 1027
		}];
	}
}