<?php
/**
 * ====================================
 * 客服二维码
 * ====================================
 * Author: 9006758
 * Date: 
 * ====================================
 * Project: new.m.chinaskin.cn
 * File: RotateModel.class.php
 * ====================================
 */
namespace Cpanel\Model;
use Common\Model\CpanelModel;
class QrcodeModel extends CpanelModel {


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $config = C('db_config.1');
        $this->connection = array_merge($config['CONFIG'], array('DB_TYPE' => C('DB_TYPE')));
        $this->tablePrefix = $this->connection['DB_PREFIX'];
        $this->tableName = 'customer_qrcode';
    }

    public function filter(&$params){
        if(!empty($params['keywords'])){
            $keyword = trim($params['keywords']);
            $map['real_name'] = $keyword;
            $map['job_number'] = $keyword;
            $map['_logic'] = 'OR';
            $this->where($map);
        }
        if(!empty($params['sort']) &&!empty($params['order'])){
            $this->order($params['sort'].' '.$params['order']);
        }
        $this->field('id,job_number,real_name,weixin,create_time,is_show,qrcode_id,show_time,locked,kefu_qrcode');

        return $this;
    }

    public function _after_select(&$resultSet,$options){
        foreach($resultSet as $key=>&$val){
            $locked = $val['locked'];
            $is_show = $val['is_show'];
            $val['kefu_qrcode'] = '<img src="'.$val['kefu_qrcode'].'" style="width:50px; height:50px;">';
            $val['locked'] = '<a href="javascript:;" onclick="lockShow(this,'.$locked.');" data-type="lock" data_id="'.$val['id'].'" class="easyui-linkbutton"><span style="font-size:18px;" class="fa '.($locked==0?'fa-check green':'fa-close red').'"> </span></a>';
            $val['is_show'] = '<a href="javascript:;" onclick="lockShow(this,'.$is_show.');" data-type="show" data_id="'.$val['id'].'" class="easyui-linkbutton"><span style="font-size:18px;" class="fa '.($is_show==0?'fa-check green':'fa-close red').'"> </span></a>';

        }
    }

}