<?php
/**
 * Created by PhpStorm.
 * User: 9009078
 * Date: 2017/1/17
 * Time: 15:58
 */
namespace Cpanel\Model;

use Common\Model\CpanelModel;

class TimingSendTplModel extends CpanelModel
{

    protected $_validate = array(
        array('msg_body','require','{%MSG_BODY_LOST}'),
        array('interval_mins','require','{%INTERVAL_MINS_LOST}'),
//        array('interval_mins','checkInterval','{%INTERVAL_MINS_MAX}',1,'callback'),
        array('max_send_nums','require','{%MAX_SEND_NUMS_LOST}'),
        array('max_send_nums','/^\d+$/','{%MAX_SEND_NUMS_IS_NUM}',1,''),
    );

    protected function checkInterval($value){
        return ($value >=120) ? true : false;
    }

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->connection = 'CPANEL';
        $this->tablePrefix = 'py_';
        $this->tableName = 'timing_send_tpl';
    }
}