<?php
/**
 * Created by PhpStorm.
 * User: 9009078
 * Date: 2017/1/18
 * Time: 11:31
 */
namespace Cpanel\Model;
use Common\Model\CpanelModel;

class UserActivityModel extends CpanelModel
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->connection = 'CPANEL';
        $this->tablePrefix = 'py_';
        $this->tableName = 'user_activity';
    }
}