<?php
/**
 * Created by PhpStorm.
 * User: 9009078
 * Date: 2017/1/17
 * Time: 11:30
 */
namespace Cpanel\Controller;
use Common\Controller\CpanelController;
use Common\Extend\WechatSendMessageTemplate;
use Common\Extend\Wechat;

class TimingSendTplController extends CpanelController{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->connection = 'CPANEL';
        $this->tablePrefix = 'py_';
        $this->tableName = 'timing_send_tpl';
    }
	
	/**
    *	发送模版内容
    *	@return exit
    */
	public function TemplateTest(){
		$openid = I('request.openid','','trim');
		$msg_body = I('request.msg_body','','trim');
		if($openid == ''){
			$this->error('请输入微信公众号ID');
		}
		if($msg_body == ''){
			$this->error('请输入需要测试的模版内容');
		}
		$WechatSendMessageTemplate = new WechatSendMessageTemplate();
		$msg_body = $WechatSendMessageTemplate->resolveTpl($msg_body, $openid);  //解析内容模版
		Wechat::$userOpenId = $openid;
        $ret = Wechat::serviceText($msg_body);
		if($ret['errcode'] == 0){
			$this->success('发送成功！');
		}else{
			$this->error($ret['errmsg']);
		}
	}
}